---
title: "MiaM_Functional Analysis_PICRUST"
output: html_document
---
  
# Install pakages
```{r}
library(dplyr)
library(tidyverse)
library(phyloseq)
library(ggpicrust2)
library(ggplot2)
library(ggrepel)
```

# Load datasets
```{r}
meta = readRDS('phyloseq_taxonomy.rds') %>% 
  .@sam_data %>% data.frame() %>% 
  rownames_to_column('sample_names')

path = read.delim('path_abun_unstrat.tsv', 
                  row.names = 1, check.names = FALSE)

# Keep only samples present in both metadata and pathway table
common_samples <- intersect(meta$sample_names, colnames(path))

meta <- meta %>%
  filter(sample_names %in% common_samples)

path <- path %>%
  dplyr::select(all_of(common_samples))

meta <- meta %>%
  slice(match(colnames(path), sample_names))

# Set 10 days as reference level
meta$Time_of_Collection_categorical <- factor(
  meta$Time_of_Collection_categorical,
  levels = c("10_days", "30_days"))

dose_levels <- unique(meta$dose)
```
# --------------------------------------------------------
# Aim3: 
# Compare functional pathways between 
# 10d vs 30d across different radiation dose groups
# --------------------------------------------------------

# Run differential analysis seperately for each radiation dose (0.0, 0.1, 0.25)
```{r}
all_results <- lapply(dose_levels, function(d) { 
  
  meta_d <- meta %>% filter(dose == d)
 
  path_filt <- path %>% dplyr::select(all_of(meta_d$sample_names))
  
  meta_d <- meta_d %>% slice(match(colnames(path_filt), sample_names))
  
  res <- pathway_daa(
    abundance  = path_filt,
    metadata   = meta_d,
    group      = "Time_of_Collection_categorical",
    daa_method = "LinDA",
    reference  = "10_days")
  res$dose <- d
  res
})

# Combine all dose results into one dataframe
daa_results_df <- bind_rows(all_results)
```
# Apply threshold & Keep only statistically significant pathways
```{r}
significant <- daa_results_df %>%
  filter(p_adjust < 0.05, abs(log2FoldChange) > 1) %>%
  arrange(dose, p_adjust) %>%
  select(dose, feature, log2FoldChange, p_values, p_adjust, group1, group2) %>%
  mutate(direction = ifelse(log2FoldChange > 0, "Higher at 30_days", "Higher at 10_days"))
significant #37 pathways found
```
# Making Visual- Volcano plot
```{r}
volcano_df <- daa_results_df %>%
  mutate(
    neglogFDR = -log10(p_adjust),
    sig = p_adjust < 0.05)

label_df <- volcano_df %>%
  filter(sig) %>%
  group_by(dose) %>%
  slice_min(p_adjust, n = 5)

volcano_plot <- ggplot(volcano_df, aes(x = log2FoldChange, y = neglogFDR)) +
  geom_point(aes(color = sig), alpha = 0.8, size = 2) +
  geom_text_repel(
    data = label_df,
    aes(label = feature),
    size = 3,
    box.padding = 0.3,
    point.padding = 0.2,
    max.overlaps = 20) +
  facet_wrap(~dose, labeller = labeller(dose = function(x) paste(x, "Gy"))) +
  geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.4) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", linewidth = 0.4) +
  scale_color_manual(
    values = c("FALSE" = "grey75", "TRUE" = "#D55E00"),
    labels = c("No", "Yes"),
    name = "Significant?") +
  labs(
    title = "Predicted Functional Pathways Differ Between 10 and 30 Days Post-exposure",
    subtitle = "Differential pathway abundance within each radiation dose group",
    x = "Higher at 10 days  \u2190  log2 fold change  \u2192  Higher at 30 days",
    y = expression(-log[10]("FDR"))
  ) +
  theme_classic(base_size = 13) +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(size = 11),
    strip.background = element_rect(fill = "grey95", color = "black", linewidth = 0.3),
    strip.text = element_text(face = "bold"),
    legend.position = "right",
    axis.title = element_text(face = "bold"),
    axis.text = element_text(color = "black"))

volcano_plot


ggsave("Differential_Pathway_Volcano.png",
  plot = volcano_plot,
  width = 8,
  height = 6,
  dpi = 300)
```
# Volcano plot with significant panels only - 0.1 Gy & 1 Gy
```{r}
Sig_volcano1 <- ggplot(volcano_df, aes(x = log2FoldChange, y = neglogFDR)) +
  geom_point(aes(color = sig), alpha = 0.7, size = 2.5) +
  geom_text_repel(
    data = volcano_df %>% filter(sig),
    aes(label = stringr::str_trunc(description, 25)),
    size = 2.3,
    force          = 12,       
    force_pull     = 0.5,      
    direction      = "both",    
    box.padding    = 0.5,
    point.padding  = 0.4,
    segment.size   = 0.3,
    segment.color  = "grey40",
    segment.alpha  = 0.7,
    max.overlaps   = Inf,
    min.segment.length = 0,
    max.iter       = 10000,    
    seed           = 42       ) +
  facet_wrap(~dose, ncol = 1,
             scales = "free_y",   
             labeller = labeller(dose = function(x) paste(x, "Gy"))) +
  geom_vline(xintercept = 0,        linetype = "dashed", linewidth = 0.4, color = "grey30")+
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", linewidth = 0.4, color = "grey30") +
  scale_color_manual(
    values = c("FALSE" = "grey78", "TRUE" = "#D55E00"),
    labels = c("No", "Yes"),
    name   = "Significant?") +
  scale_x_continuous(expand = expansion(mult = c(0.3, 0.15))) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.15))) +
  labs(
    x = "Higher at 10 days  \u2190  log2 fold change  \u2192  Higher at 30 days",
    y = expression(-log[10]("FDR"))) +
  theme_classic(base_size = 13) +
  theme(
    strip.background = element_rect(fill = "grey95", color = "black", linewidth = 0.3),
    strip.text       = element_text(face = "bold"),
    legend.position  = "right",
    panel.border     = element_rect(color = "black", fill = NA, linewidth = 0.8),
    panel.spacing    = unit(2.5, "lines"),
    axis.title       = element_text(face = "bold"),
    axis.text        = element_text(color = "black"))

ggsave(filename = "~/MICB305 GROUP/MM_Volcano_Sig.png", 
plot = Sig_volcano1, 
width = 9, 
height = 13)
```
# Making Visuals- Bar Plot
```{r}
bar_plot <- ggplot(significant, aes(x = reorder(feature, log2FoldChange), 
                y = log2FoldChange, 
                fill = direction)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  facet_wrap(~dose, scales = "free_y") +
  scale_fill_manual(values = c("Higher at 10_days" = "#4DAF4A",
                               "Higher at 30_days" = "#E41A1C")) +
  theme_minimal() +
  labs(
    title = "Differential_Pathway_Bar",
    x = "Pathway",
    y = "Log2 Fold Change (30 days vs 10 days)",
    fill = "Direction")
bar_plot
```

