---
title: "NatsPICRUSt2"
output: html_document
---

```{r Load data and libraries}
# install.packages("devtools")
# devtools::install_github("cafferychen777/ggpicrust2")
# devtools::install_github("biobakery/Maaslin2")
# install.packages("MicrobiomeStat")
# BiocManager::install("KEGGREST")
# BiocManager::install("Maaslin2")
# BiocManager::install("MicrobiomeStat")
# install.packages("GGally")
library(tidyverse)
library(ggrepel)
library(phyloseq)
library(ggpicrust2)
library(Maaslin2)
library(MicrobiomeStat)
library(ggplot2)
library(patchwork)
```

```{r Load initial dataset for viewing}

phyloseq = readRDS("phyloseq_taxonomy.rds")

ps_rare = phyloseq %>% rarefy_even_depth(sample.size = 87521, rngseed = 12)
table(sample_sums(ps_rare))

```

```{r Load datasets for PiCRUSt2}

meta = ps_rare %>%
.@sam_data %>%
data.frame()%>%
rownames_to_column("sample_name")

ko=read.delim("path_abun_unstrat.tsv", row.names=1, 
check.names=FALSE)

```

### Running PICRUSt2

```{r Differential analysis}

#Perform pathway differential abundance analysis (DAA) using LinDA method 
daa_results_df = pathway_daa(abundance= ko,
                             metadata=meta,
                             group="Time_of_Collection_categorical",
                             daa_method="LinDA",
                             select=NULL, reference=NULL)


daa_annotated_results_df = pathway_annotation(pathway="MetaCyc", 
                                              daa_results_df=daa_results_df,
                                              ko_to_kegg=FALSE)

saveRDS(daa_annotated_results_df,"daa_annotated_results_df.rds")

daa_annotated_results_df = readRDS("daa_annotated_results_df.rds")
view(daa_annotated_results_df)

```


```{r new meta for each dose}

meta0 <- meta |>
filter(dose_categorical == "0_dose")


meta01 <- meta |>
filter(dose_categorical == "0.1_dose")


meta025 <- meta |>
filter(dose_categorical == "0.25_dose")


meta1 <- meta |>
filter(dose_categorical == "1_dose")

```

##Running DAA by time point 4 times, once per dose

```{r}

# for dose 0 Gy
daa_results_0 = pathway_daa(abundance= ko,
                             metadata=meta0,
                             group="Time_of_Collection_categorical",
                             daa_method="LinDA",
                             select=NULL, 
                             reference="Time_of_Collection_categorical")

daa_annotated_dose_0 = pathway_annotation(pathway="MetaCyc", 
                                              daa_results_df=daa_results_0,
                                              ko_to_kegg=FALSE)


# for dose 0.1Gy
daa_results_01 = pathway_daa(abundance= ko,
                             metadata=meta01,
                             group="Time_of_Collection_categorical",
                             daa_method="LinDA",
                             select=NULL, 
                             reference="Time_of_Collection_categorical")

daa_annotated_dose_01 = pathway_annotation(pathway="MetaCyc", 
                                              daa_results_df=daa_results_01,
                                              ko_to_kegg=FALSE)

# for dose 0.25Gy
daa_results_025 = pathway_daa(abundance= ko,
                             metadata=meta025,
                             group="Time_of_Collection_categorical",
                             daa_method="LinDA",
                             select=NULL, 
                             reference="Time_of_Collection_categorical:10_days")


daa_annotated_dose_025 = pathway_annotation(pathway="MetaCyc", 
                                              daa_results_df=daa_results_025,
                                              ko_to_kegg=FALSE)

# for dose 1 Gy
daa_results_1 = pathway_daa(abundance= ko,
                             metadata=meta1,
                             group="Time_of_Collection_categorical",
                             daa_method="LinDA",
                             select=NULL, 
                             reference="Time_of_Collection_categorical")

daa_annotated_dose_1 = pathway_annotation(pathway="MetaCyc", 
                                              daa_results_df=daa_results_1,
                                              ko_to_kegg=FALSE)

```

```{r volcano plots}

#0 gy
plot_data_0 <- daa_annotated_dose_0 %>%
  mutate(significant = p_adjust<0.05 & abs(log2_fold_change) >=1)
  
volcano_0 <- ggplot(plot_data_0, aes(x=p_adjust, y=log2_fold_change, colour=significant))+ 
geom_point(size=3, alpha=0.7) + 
theme_minimal() +
scale_color_manual(values = c("TRUE" = "thistle1", "FALSE" = "olivedrab")) +geom_vline(xintercept = 0.05, linetype = "dashed", alpha = 0.5) + geom_hline(yintercept = c(-1,1), linetype = "dashed", alpha=0.5)+
labs(title = "0 Gy", x = "P values", y = "log 2 fold change") + theme(legend.position = "bottom")+
  scale_y_continuous(limits = c(-5,5))+
  scale_x_continuous(limits=c(-0.5,1))+
  theme( plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    legend.position = "bottom"
  )


volcano_0

#0.1 Gy
plot_data_01 <- daa_annotated_dose_01 %>%
  mutate(significant = p_adjust<0.05 & abs(log2_fold_change) >=1)
  
volcano_01 <- ggplot(plot_data_01, aes(x=p_adjust, y=log2_fold_change, colour=significant)) + 
geom_point(size=3, alpha=0.7) + 
theme_minimal() +
scale_color_manual(values = c("TRUE" = "thistle1", "FALSE" = "olivedrab")) +geom_vline(xintercept = 0.05, linetype = "dashed", alpha = 0.5) + geom_hline(yintercept = c(-1,1), linetype = "dashed", alpha=0.5)+
labs(title = "0.1 Gy", x = "P values", y = "log 2 fold change") + theme(legend.position = "bottom")+
  scale_y_continuous(limits = c(-5,5))+
  scale_x_continuous(limits=c(-0.5,1))+theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    legend.position = "bottom"
  )

volcano_01

#0.25 Gy

plot_data_025 <- daa_annotated_dose_025 %>%
  mutate(significant = p_adjust<0.05 & abs(log2_fold_change) >=1)
  
volcano_025 <- ggplot(plot_data_025, aes(x=p_adjust, y=log2_fold_change, colour=significant)) + 
geom_point(size=3, alpha=0.7) + 
theme_minimal() +
scale_color_manual(values = c("TRUE" = "thistle1", "FALSE" = "olivedrab")) +geom_vline(xintercept = 0.05, linetype = "dashed", alpha = 0.5) + geom_hline(yintercept = c(-1,1), linetype = "dashed", alpha=0.5)+
labs(title = "0.25 Gy", x = "P values", y = "log 2 fold change") + theme(legend.position = "bottom")+
  scale_y_continuous(limits = c(-5,5))+
  scale_x_continuous(limits=c(-0.5,1))+theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    legend.position = "bottom"
  )

volcano_025


#1Gy
plot_data_1 <- daa_annotated_dose_1 %>%
  mutate(significant = p_adjust<0.05 & abs(log2_fold_change) >=1)
  
volcano_1 <- ggplot(plot_data_1, aes(x=p_adjust, y=log2_fold_change, colour=significant)) + 
geom_point(size=3, alpha=0.7) + 
theme_minimal() +
scale_color_manual(values = c("TRUE" = "thistle1", "FALSE" = "olivedrab")) +geom_vline(xintercept = 0.05, linetype = "dashed", alpha = 0.5) + geom_hline(yintercept = c(-1,1), linetype = "dashed", alpha=0.5)+
labs(title = "1Gy", x = "P values", y = "log 2 fold change") + theme(legend.position = "bottom")+
  scale_y_continuous(limits = c(-5,5))+
  scale_x_continuous(limits=c(-0.5,1))+theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    legend.position = "bottom"
  )


volcano_1

all_volcano <- (volcano_0+volcano_01)/(volcano_025+volcano_1)
all_volcano

ggsave("~/Desktop/group_project/All_dose_volcano.png", 
	plot=all_volcano, width=20, height=20, limitsize = FALSE) 

```

```{r}

# dose 0 Gy has no significant output 

daa_annotated_dose_0 |>
  filter(p_adjust < 0.05, abs(log2_fold_change) >=1 | abs(log2_fold_change) <=-1) |>
nrow()

# dose 0.1Gy has no significant output 

daa_annotated_dose_01 |>
  filter(p_adjust < 0.05, abs(log2_fold_change) >=1) |>
nrow()


# dose 0.25Gy has no significant ouput 

daa_annotated_dose_025 |>
  filter(p_adjust < 0.05, abs(log2_fold_change) >=1) |>
nrow()


# dose 1 Gy has significant output!

daa_annotated_dose_1 |>
  filter(p_adjust < 0.05, abs(log2_fold_change) >=1) |>
nrow()

top_1=daa_annotated_dose_1 |>
  filter(p_adjust<0.05, abs(log2_fold_change)>=1) |>
  arrange(p_adjust)
 
ko_significant <- ko[rownames(ko) %in% top_1$feature,
                     colnames(ko) %in% meta1$sample_name]

source("~/Desktop/group_project/ggpicrust2_errorbar_function_fixed.R")
 

peb1=pathway_errorbar_fixed(abundance=ko_significant,
                  daa_results_df=top_1,
                  Group=meta1$Time_of_Collection_categorical,
                  wrap_label=T, wraplength=10,
                  fc_cutoff=F, order_by_log=F,
                  p_values_threshold=0.05,
                  order= "group",
                  ko_to_kegg=FALSE,
                  p_value_bar=TRUE,
                  x_lab="description")
                  

 
ggsave("peb1.png", plot=peb1, width=35, height=15, limitsize=FALSE)

#All this data aligns with the expected data obtained from the volcano plot
#where only 1Gy has significant outputs 

```

```{r}

# Check how many pass p_adjust only
daa_annotated_dose_0 |> 
  filter(p_adjust < 0.05) |>
  nrow()
daa_annotated_dose_01 |> 
  filter(p_adjust < 0.05) |> 
  nrow()
daa_annotated_dose_025 |> 
  filter(p_adjust < 0.05) |> 
  nrow()
daa_annotated_dose_1 |> 
  filter(p_adjust < 0.05) |> 
  nrow()

# Check how many pass fold change only
daa_annotated_dose_0 |> 
  filter(abs(log2_fold_change) >= 1) |> 
  nrow()
daa_annotated_dose_01 |> 
  filter(abs(log2_fold_change) >= 1) |> 
  nrow()
daa_annotated_dose_025 |> 
  filter(abs(log2_fold_change) >= 1) |> 
  nrow()
daa_annotated_dose_1 |> 
  filter(abs(log2_fold_change) >= 1) |> 
  nrow()


```
